language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_ab46abe2afd1_key -iv $encrypted_ab46abe2afd1_iv
    -in travis_ci_rsa.enc -out ./travis_ci_rsa -d
  - set -e
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn run test
  - yarn run build
after_success:
  - codecov
